#!/usr/bin/python
import sys
import shutil
import magic
import subprocess
from os import path

def is_image(file):
    if not path.isfile(file):
        return False

    mime = magic.from_file(file, mime=True).decode('UTF-8')
    if mime.startswith('image'):
        return True
    return False

def sort_by_type(files):
    images = []
    others = []
    for f in files:
        if is_image(f):
            images.append(f)
        else:
            others.append(f)
    return images, others

def copy_to_clipboard(url):
    if not shutil.which('xclip'):
        return

    echo = subprocess.Popen(['echo', url], stdout=subprocess.PIPE)
    subprocess.Popen(['xclip', '-selection', 'clipboard'], stdin=echo.stdout)

    print("Copied url to clipboard", file=sys.stderr)

def make_url(fil, path):
    return 'https://upload.edholmarna.se/' + path + fil

def upload(files, to_path):
    if not files:
        return 0
    scp = ['scp']
    scp.extend(files)
    scp.append('jupiter:' + to_path)
    return subprocess.call(scp)


def main():
    files = sys.argv[1:]
    images, others = sort_by_type(files)
    to_paths = {'images': 'upload/images',
                'others': 'upload'}

    if upload(images, to_paths['images']) != 0:
        print('Failed to upload image(s)', file=sys.stderr)
    if upload(others, to_paths['others']) != 0:
        print('Failed to upload file(s)', file=sys.stderr)

    if len(files) == 1:
        # If we only uploaded one file, copy the link
        fil = path.basename(files[0])
        to_path = ''
        if is_image(files[0]):
            to_path = 'images/'
        copy_to_clipboard(make_url(fil, to_path))


if __name__ == '__main__':
    main()
